<?php

namespace Proxies\__CG__\PlanningInsta2015\PlanningInsta2015Bundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Eleve extends \PlanningInsta2015\PlanningInsta2015Bundle\Entity\Eleve implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'ideleve', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'nom', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'prenom', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'age', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'adresse', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'promopromo', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'idpromo', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'id', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'User', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'promo');
        }

        return array('__isInitialized__', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'ideleve', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'nom', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'prenom', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'age', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'adresse', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'promopromo', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'idpromo', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'id', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'User', '' . "\0" . 'PlanningInsta2015\\PlanningInsta2015Bundle\\Entity\\Eleve' . "\0" . 'promo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Eleve $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getIdeleve()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdeleve', array());

        return parent::getIdeleve();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setPrenom($prenom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPrenom', array($prenom));

        return parent::setPrenom($prenom);
    }

    /**
     * {@inheritDoc}
     */
    public function getPrenom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPrenom', array());

        return parent::getPrenom();
    }

    /**
     * {@inheritDoc}
     */
    public function setAge($age)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAge', array($age));

        return parent::setAge($age);
    }

    /**
     * {@inheritDoc}
     */
    public function getAge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAge', array());

        return parent::getAge();
    }

    /**
     * {@inheritDoc}
     */
    public function setAdresse($adresse)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAdresse', array($adresse));

        return parent::setAdresse($adresse);
    }

    /**
     * {@inheritDoc}
     */
    public function getAdresse()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAdresse', array());

        return parent::getAdresse();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdpromo(\PlanningInsta2015\PlanningInsta2015Bundle\Entity\Promo $idpromo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdpromo', array($idpromo));

        return parent::setIdpromo($idpromo);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdpromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdpromo', array());

        return parent::getIdpromo();
    }

    /**
     * {@inheritDoc}
     */
    public function setIdeleve($ideleve)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdeleve', array($ideleve));

        return parent::setIdeleve($ideleve);
    }

    /**
     * {@inheritDoc}
     */
    public function setPromopromo(\PlanningInsta2015\PlanningInsta2015Bundle\Entity\Promo $promopromo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromopromo', array($promopromo));

        return parent::setPromopromo($promopromo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromopromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromopromo', array());

        return parent::getPromopromo();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function addUser(\PlanningInsta2015\PlanningInsta2015Bundle\Entity\Eleve $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addUser', array($user));

        return parent::addUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function removeUser(\PlanningInsta2015\PlanningInsta2015Bundle\Entity\Eleve $user)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeUser', array($user));

        return parent::removeUser($user);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setPromo(\PlanningInsta2015\PlanningInsta2015Bundle\Entity\Promo $promo = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPromo', array($promo));

        return parent::setPromo($promo);
    }

    /**
     * {@inheritDoc}
     */
    public function getPromo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPromo', array());

        return parent::getPromo();
    }

}
