PlanningInsta2015\PlanningInsta2015Bundle\Entity\User:
    type: entity
    table: user
    indexes:
        fk_eleve_idx:
            columns:
                - eleve_id
        fk_professeur_idx:
            columns:
                - professeur_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        haspc:
            type: boolean
            nullable: true
            comment: ''
        mdp:
            type: string
            nullable: true
            length: 32
            fixed: false
            comment: ''
        login:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToOne:
        eleve:
            targetEntity: Eleve
            cascade: {  }
            inversedBy: User
            joinColumns:
                eleve_id:
                    referencedColumnName: id
            orphanRemoval: false
        professeur:
            targetEntity: Professeur
            cascade: {  }
            inversedBy: User
            joinColumns:
                professeur_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
