Planning:
    type: entity
    table: planning
    indexes:
        fk_cours_idx:
            columns:
                - cours_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        dateDebut:
            type: datetime
            nullable: true
            comment: ''
            column: date_debut
        dateFin:
            type: datetime
            nullable: true
            comment: ''
            column: date_fin
    manyToOne:
        cours:
            targetEntity: Cours
            cascade: {  }
            inversedBy: Cours
            joinColumns:
                name:cours_id
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
