PlanningInsta2015\PlanningInsta2015Bundle\Entity\Promo:
    type: entity
    table: promo
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        numero:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        formation:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    lifecycleCallbacks: {  }
    oneToMany:
        Eleve:
            targetEntity: Promo
            cascade: {  }
            mappedBy: Promo
            joinColumns:
                id:
                    referencedColumnName: promo_id